olevba 0.60.1 on Python 3.8.10 - http://decalage.info/python/oletools
ERROR    Unhandled exception in main: Error -3 while decompressing data: invalid code -- missing end-of-block
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/oletools/olevba.py", line 4649, in main
    curr_return_code = process_file(filename, data, container, options)
  File "/usr/local/lib/python3.8/dist-packages/oletools/olevba.py", line 4452, in process_file
    vba_parser = VBA_Parser_CLI(filename, data=data, container=container,
  File "/usr/local/lib/python3.8/dist-packages/oletools/olevba.py", line 4011, in __init__
    super(VBA_Parser_CLI, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/oletools/olevba.py", line 2736, in __init__
    self.ftg = ftguess.FileTypeGuesser(self.filename, data=data)
  File "/usr/local/lib/python3.8/dist-packages/oletools/ftguess.py", line 777, in __init__
    if FType_Generic_OpenXML.recognize(self):
  File "/usr/local/lib/python3.8/dist-packages/oletools/ftguess.py", line 395, in recognize
    root_rels = ftg.zipfile.read('_rels/.rels')
  File "/usr/lib/python3.8/zipfile.py", line 1476, in read
    return fp.read()
  File "/usr/lib/python3.8/zipfile.py", line 926, in read
    buf += self._read1(self.MAX_N)
  File "/usr/lib/python3.8/zipfile.py", line 1016, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid code -- missing end-of-block
